name: Dependabot
on:
  # This workflow needs to add a commit to the dependabot PR, so it needs write access
  # to the repository containing dependabot's branch. Unfortunately this is the base
  # repo rather than a fork made by dependabot. We don't want a bad actor to be able
  # to run this workflow and exploit a GITHUB_TOKEN with write permissions. See
  # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
  #
  # To mitigate this:
  # - we require a dependabot branchname, and that the PR author is dependabot
  # - we only run trusted actions and workflows
  # - we only request the write permissions that we need
  pull_request_target:
    paths:
      # This requires the lockfile to change, but will also trigger if other files have
      # changed too.
      - "poetry.lock"

permissions:
  contents: write

jobs:
  echo2:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ startsWith(github.head_ref, 'dependabot/') }}
          echo ${{ github.actor == 'dependabot[bot]' }}
          echo ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
          echo ${{       startsWith(github.head_ref, 'dependabot/') && github.actor == 'dependabot[bot]' && github.event.pull_request.user.login == 'dependabot[bot]' }}

  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
    if: >
      startsWith(github.head_ref, 'dependabot/')
      && github.actor == 'dependabot[bot]'
      && github.event.pull_request.user.login == 'dependabot[bot]'

#  changelog:
#    # The `github.actor` invocation is recommended by
#    # https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions
#    if: ${{ github.actor == 'dependabot[bot]' && github.event.pull_request.user.login == 'dependabot[bot]' }}
#    uses: "matrix-org/backend-meta/.github/workflows/dependabot.yml@dmr/dependabot"
#    with:
#      pull-request-number: ${{ github.event.number }}
#      head-ref: ${{ github.event.pull_request.head.ref }}
#      head-sha: ${{ github.event.pull_request.head.sha }}
